#!/bin/bash
set -efuo pipefail

function main
{
	if [ "$(unstaged-changes | wc -l)" -gt 0 ]
	then
		echo 'Warning: you have unstaged changes:'
		unstaged-changes
	else
		require-render-success
		./util/find-orphaned-files.sh
	fi
}

function unstaged-changes
{
	# Unstaged changes have a non-' ' char in the second column:
	git status --porcelain | grep -Eve '^.  '
}

function require-render-success
{
	# BUG: This succeeds even if there are warnings. There is no `--deny-warnings` equivalent for `mdbook` AFAICT.
	mdbook build
}

main "$@"

source ./util/run-local-hook.sh
