[book]
authors = ["Nate Wilcox"]
language = "en"
multilingual = false
src = "src"
title = "Zcash Trailing Finality Layer"

[preprocessor.graphviz]
command = "mdbook-graphviz"
after = ["links"]
output-to-file = true
