name: Content Improvement
description: A content improvement
labels: ["content improvement"]
assignees:
  - nathan-at-least
body:
  - type: markdown
    attributes:
      value: Thanks for suggesting an improvement!
  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
      description: Suggest anything from wording improvements to technical or design changes.
    validations:
      required: true
