name: Rendering or Infrastructure Issue
description: A problem with rendering, automation, or other infrastructure
labels: ["infrastructure"]
assignees:
  - nathan-at-least
body:
  - type: markdown
    attributes:
      value: Thanks for helping out!
  - type: textarea
    id: problem
    attributes:
      label: What is the problem?
      description: Please report rendering problems or other tooling / infrastructure problems.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Do you recommend a solution?
      description: If you have a suggested solution, please share!
    validations:
      required: false
