name: 'Check Rendering'
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  check-render:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: graphviz
        version: 1.0
    - uses: taiki-e/cache-cargo-install-action@v1
      with:
        tool: mdbook@0.4.19
    - uses: taiki-e/cache-cargo-install-action@v1
      with:
        tool: mdbook-graphviz@0.1.6
    - uses: actions/checkout@v3
    - run: mdbook build


