name: 'Check Rendering'
on: [push, pull_request]
jobs:
  check-render:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'
    - run: cargo install mdbook-graphviz
    - uses: actions/checkout@v3
    - run: mdbook build


