name: 'Check Rendering'
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  check-render:
    runs-on: 'ubuntu-latest'
    steps:
    - name: cache rendering tools
      id: cache-mdbook-graphviz-components
      uses: actions/cache@v3
      with:
        path: |
          /usr/bin/dot
          ~/.cargo/bin/mdbook
          ~/.cargo/bin/mdbook-graphviz
        key: ${{ runner.os }}-${{ runner.arch }}-mdbook-graphviz-components
    - if: ${{ steps.cache-mdbook-graphviz-components.outputs.cache-hit != 'true' }}
      run: sudo apt-get install graphviz
    - if: ${{ steps.cache-mdbook-graphviz-components.outputs.cache-hit != 'true' }}
      run: cargo install mdbook
    - if: ${{ steps.cache-mdbook-graphviz-components.outputs.cache-hit != 'true' }}
      run: cargo install mdbook-graphviz
    - uses: actions/checkout@v3
    - run: mdbook build


