name: 'Check Rendering'
on: [push, pull_request]
jobs:
  check-render:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'
    - name: cache mdbook-graphviz
      id: cache-mdbook-graphviz
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/mdbook-graphviz
        key: ${{ runner.os }}-mdbook-graphviz
    - if: ${{ steps.cache-mdbook-graphviz.outputs.cache-hit != 'true' }}
      run: cargo install mdbook-graphviz
    - uses: actions/checkout@v3
    - run: mdbook build


