name: 'Check Rendering'
on: pull_request
jobs:
  check-render:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Rust Toolchain Version Diagnostics
      run: cargo --version --verbose && rustup --version
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - uses: taiki-e/cache-cargo-install-action@v1
      with:
        tool: mdbook@0.4.29
    - uses: taiki-e/cache-cargo-install-action@v1
      with:
        tool: mdbook-graphviz@0.1.6
    - uses: actions/checkout@v3
    - run: mdbook build
    - name: Check for Orphaned Files
      run: ./util/find-orphaned-files.sh
